# Generated by Django 4.0.3 on 2022-03-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('think', '0002_profile_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
    ]
